### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
Found some misspellings.

~~This is an all or nothing PR.~~
Let's distance ourselves from programming lingo.

```diff
- CatchedType
+ CaughtType
```

- Catched-22
- Catchedphrase
- [C. C. Catched](https://kep.cdn.indexvas.hu/1/0/4723/47237/472377/47237720_3601580_d2f490e2f3654b12aa452b1e53b36c12_wm.jpg)
- Catched and release
- Catcheder in the Rye 📖 

inspiration @iandelmar

### CODE REVIEW

**Comment by TomasVotruba** [comment]
It might be better to use `SomeType` to make it simple

**Comment by szepeviktor** [comment]
All right. Going in ...

**Comment by szepeviktor** [comment]
Done 🍏

**Comment by TomasVotruba** [comment]
Awesome, thanks :+1:

**Comment by szepeviktor** [comment]
Glad to contribute to Tomas Projects.

**Pull request merged**
